### ISSUE TITLE
Publish new changes

### ISSUE THREAD

**Issue by ablewalmsley** [openvenues/node-postal#28]
It doesn't seem like there is an NPM update available after the new pull request just got merged (#25) that supports node v12.  Is that something that can be added?  As a temporary measure I've been using the forked repo https://github.com/kembuco/node-postal as my dependency, but would like to switch back to this repo as soon as it gets published.

**Comment by missinglink** [comment]
Hi @albarrentine thanks for granting @orangejulius and I `owner` on this repo, we can manage this issue along with future publishing of the `npm` module 🎉 

In order to actually publish them we need access to push the [node-postal](https://www.npmjs.com/package/node-postal) module up to the registry 🔐 

I had a look at who currently has access it's unfortunately using an email address that's been gone for some time:

```bash
npm owner ls
albarrentine <pelias@mapzen.com>
```

Do you possible remember the password or have access to a computer that is still authenticated with `npm` on the command line?

If so you can add me as an owner and I can handle the rest:

```bash
npm owner add missinglink
```

If not.. then we're in a little bit of a pickle and it might require contacting `npm` to regain access to the module 🤷‍♂️

**Comment by RickyRomero** [comment]
@missinglink If you can't get access to the npm registry entry, would you mind tagging a new version in Git and publishing a release here? https://github.com/openvenues/node-postal/releases

It's possible to add a dependency from a URL to a release tarball.
https://atmos.washington.edu/~nbren12/reports/journal/2018-07-16-NN-conservation/node_modules/npm/html/doc/cli/npm-install.html
```sh
npm install https://github.com/indexzero/forever/tarball/v0.5.6
```

For now I've simply added the `master` branch to my package.json, but that's not tenable long-term.
```sh
yarn add node-postal@https\://github.com/openvenues/node-postal.git
```

**Comment by missinglink** [comment]
Hi @RickyRomero sorry for the delay, I have been travelling this week.

I've contacted npm support, my preference would be that we publish via `npm` again (and likely also tag releases) rather than purely relying on git tags, so let's wait a couple days for their response before proceeding.

In lieu of a tagged release I would suggest you target the commit hash rather than the branch. 

eg:
```
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
```

**Comment by abdulrahman-khankan** [comment]
You can contact the NPM support to request control over the npm package name. They are usually super helpful in such cases.
https://www.npmjs.com/policies/disputes

**Comment by missinglink** [comment]
I've submitted a request via that think. After the `HTTP POST` it returned the 404 page, so hopefully everything got submitted ok 🤷‍♂️

**Comment by abdulrahman-khankan** [comment]
According to that page, you should receive an automated email after submitting the request if it was successful.

**Comment by missinglink** [comment]
Oh you know what, I looked in my spam and this was actually processed in Oct 2020 🙄 

```bash
npm owner ls node-postal
missinglink <npm@rcpt.at>
```

**Comment by missinglink** [comment]
Okay, so I'm happy to do this although TBH I've kinda forgotten where we're at.
The latest published version on npm is [1.0.0](https://www.npmjs.com/package/node-postal).

I need to figure out:
- Which commit that corresponded to
- Which commits have come since and their effect on the semver versioning (ie. were they breaking or not)

Then I think I'll got through and publish all the missing releases as their own versions, including the latest.
That way if I break anything then people can simply peg to a specific version while we fix it.

How does that sound?

**Comment by missinglink** [comment]
```bash
npm view node-postal@1.0.0 --json | jq .time
{
  "modified": "2020-10-28T20:09:31.647Z",
  "created": "2016-08-04T17:36:43.450Z",
  "0.3.0": "2016-08-04T17:36:43.450Z",
  "1.0.0": "2017-04-06T07:41:42.321Z"
}
```

So I'm assuming it's https://github.com/openvenues/node-postal/pull/13 meaning there's 8 commits since then.

**Comment by missinglink** [comment]
I've tagged that commit with `v1.0.0`

```bash
/code/openvenues/node-postal master ❯ git tag -a 'v1.0.0' 81925e6e928ebc2da912bca33588f522ebb33046

/code/openv/node-postal master ❯ git push --tags
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 176 bytes | 176.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:openvenues/node-postal.git
 * [new tag]         v1.0.0 -> v1.0.0
 ```

**Comment by abdulrahman-khankan** [comment]
Awesome news!

If it gets too complicated to know the effect of each commit, an alternative would be to just publish the current version on master as v2.0.0

**Comment by missinglink** [comment]
I think this will work, I just did the first one:

```bash
git tag -a 'v1.0.1' e16e083c280a95228776086aa33c4661704d87d7
git checkout v1.0.1
npm version 1.0.1
npm publish
```

**Comment by missinglink** [comment]
```bash
git tag -a 'v1.0.2' 97c78c2904822a9e848cbf200dbb93de5170882e
git checkout v1.0.2
npm version 1.0.2
npm publish
npm notice
npm notice 📦  node-postal@1.0.2
npm notice === Tarball Contents ===
npm notice 787B  .travis.yml
npm notice 1.1kB LICENSE
npm notice 4.0kB README.md
npm notice 726B  binding.gyp
npm notice 106B  index.js
npm notice 942B  package.json
npm notice 7.5kB src/expand.cc
npm notice 3.2kB src/parser.cc
npm notice 2.2kB test/index.test.js
npm notice === Tarball Details ===
npm notice name:          node-postal
npm notice version:       1.0.2
npm notice filename:      node-postal-1.0.2.tgz
npm notice package size:  6.1 kB
npm notice unpacked size: 20.5 kB
npm notice shasum:        46c66bd800ed8d0d4f65005727f634f68c79e0db
npm notice integrity:     sha512-yTri4MXiUAjAP[...]6eTsb7CD0axjA==
npm notice total files:   9
npm notice
This operation requires a one-time password.
Enter OTP: xxxxxx
+ node-postal@1.0.2
```

**Comment by missinglink** [comment]
okay so here's the new commits, some were just merge commits so I skipped them:

```bash
git tag -a 'v1.0.0' 81925e6e928ebc2da912bca33588f522ebb33046
git tag -a 'v1.0.1' e16e083c280a95228776086aa33c4661704d87d7
git tag -a 'v1.0.2' 97c78c2904822a9e848cbf200dbb93de5170882e
git tag -a 'v1.0.3' f826ea6b5cc8e5e749baa37745d5d8bdef25f6e7
git tag -a 'v1.0.4' 7b6b167b27cf0c071da000a5bd13170f22fb9e18
git tag -a 'v1.0.5' e1687b54ca08eccd706a28d3ac07b0618884422d
git tag -a 'v1.1.0' cafbaf17692fb703ca8e5dc87f641b89fcac4ba1
```

The latest is [v.1.1.0](https://www.npmjs.com/package/node-postal) which contains https://github.com/openvenues/node-postal/pull/25

**Comment by missinglink** [comment]
Is there anything else that needs to be done here or can we close this? Do we want a `2.0` release?

Going forward I'd like to switch to GH Actions from Travis and maybe use `semantic-release` or something like that to make this less manual.

**Comment by missinglink** [comment]
Apologies if the version numbers don't adhere to the [semver spec](https://semver.org/), I wasn't really sure which (if any) were breaking commits.

**Comment by abdulrahman-khankan** [comment]
It look great, thanks a lot for putting the effort into this. Ideally this should handled automatically by the CI pipeline as you mentioned.
