### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pasupulaphani** [openvenues/node-postal#4]
has anyone experienced this?
```
root@f34e0cbbc3d5:/app/user# node
> require("node-postal");
Segmentation fault
```

Same using the bin directly!
```
root@f34e0cbbc3d5:/app/user# ./libpostal/src/libpostal "Quatre vignt douze Ave des Champs-lyses"
Segmentation fault
```

**Comment by thatdatabaseguy** [comment]
Can you tell me the following about your setup:

1. How much memory does your machine have available? libpostal needs at least 2G free.
2. Did you run out of disk space? If the models didn't download successfully, loading them could possibly cause a segfault. Running ```du -h -d1``` on your libpostal data directory should show something like 3.3G if everything downloaded correctly.
3. Which OS are you using, and can you post the output of ```uname -a```?

**Comment by pasupulaphani** [comment]
I'm running in a docker.

1. memory 3GB (1.5GB free)
2. 1.4G    ./libpostal
3. Ubuntu 14.04

**Comment by thatdatabaseguy** [comment]
Interesting, we were about to start looking at Docker environments.

The disk usage sounds low. Can you run ```df -h``` and make sure the disk isn't full? If not, try ```rm -rf```ing the data dir and running ```make``` again.

Memory is also on the low side for node-postal since it loads both the parser and the normalization module at once. On a modern OS like Ubuntu 14.04 it will probably work, but may have to use swap.

**Comment by pasupulaphani** [comment]
Probably it hasn't got enough memory on Docker.

**Comment by pasupulaphani** [comment]
Probably it is better for us to use a hosted service. Since we are planning to use this as one of the service that powers our autocomplete service, it should be very very fast. Do you have any suggestions?
