### ISSUE TITLE
More explicit installation instructions

### ISSUE THREAD

**Issue by jefffriesen** [openvenues/node-postal#6]
I've been hoping for something like this for a long time. I'm also hoping to get it running : ). Even though installation instructions are fairly thorough, there are a couple confusing parts I'm hoping someone can clear up for myself and others.

1. In the "Installing libpostal" section, where do we clone that? If it doesn't matter, do we need to set the PATH to the lib so `node-postal` can find it?
2. "Installing node-gyp on Linux (Ubuntu)" section: Are some of these steps needed on OSX? I assume(?) `sudo npm install -g node-gyp` is needed, but are the steps above needed?
3. Version of node required? I think `node-gyp` installs based on node version, so I would assume this would?

For both node 5.x and 6.x, I'm getting these errors:
```
~/git/jefffriesen/data-pipeline/libpostal[master+]$ npm install openvenues/node-postal --save

> node-postal@0.3.0 install /Users/jeffers/git/jefffriesen/data-pipeline/node_modules/node-postal
> (node-gyp rebuild) || (exit 0)

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/expand/src/expand.o
../src/expand.cc:1:10: fatal error: 'libpostal/libpostal.h' file not found
#include <libpostal/libpostal.h>
         ^
1 error generated.
make: *** [Release/obj.target/expand/src/expand.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeffers/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/jeffers/.nvm/versions/node/v5.10.1/bin/node" "/Users/jeffers/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jeffers/git/jefffriesen/data-pipeline/node_modules/node-postal
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

I got no errors on any of the previous install steps, unless this is an error
```
Checking for new libpostal geodb data file...
New libpostal geodb data file available
Downloading multipart: http://libpostal.s3.amazonaws.com/geodb.tar.gz, size=486746092, num_chunks=7
...
Downloading part 7: filename=/Users/jeffers/git/libpostal_data/libpostal/geodb.tar.gz.7, offset=402653184, max=486746092
make[3]: *** [all-local] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Any suggestions or clarifications on installation? Thank you

**Comment by thatdatabaseguy** [comment]
node-postal is a thin wrapper around libpostal, which is written in C and does all the heavy lifting. The C library can be found here: https://github.com/openvenues/libpostal and is also written/maintained by me. Cloning that repo is the first step under "Installing libpostal" in the instructions, and seeing the output above means you've already run the install for it.

It looks like there was an error while running ```make``` for the C library, probably related to disk space. Make sure there's at least 2.2G of disk space available in whichever directory you specified during ```./configure --datadir=[some dir]``` and that the ```make``` and ```sudo make install``` commands succeed before moving on to installing the bindings. If downloading the data files fails, subsequent steps like installing libpostal.h in /usr/local/include and libpostal.so in /usr/local/lib fail as well, hence why Node can't find them at compile-time. There shouldn't be any path manipulation needed to help the Node bindings find libpostal. /usr/local/{include,lib} should be on the default paths.

"Installing node-gyp on Linux" is just about prerequisites for Linux specifically. On Mac all the prereqs come with Xcode, so that section doesn't apply and ```sudo npm install -g node-gyp``` should be all that's needed.

The Node bindings are tested on most major versions of Node going back to 0.10 and we use a library called [Nan](https://github.com/nodejs/nan), which abstracts changes in the V8/Native C++ APIs across versions of Node. Using Nan's macros allows node-postal to stay backward-compatible and relatively future-proof since Nan is maintained by the NodeJS team.

**Comment by jefffriesen** [comment]
@thatdatabaseguy I got it running. Thank you.

It's weird - I ran the `make` script and it just gave up downloading. I was on reasonably fast, stable connections both times.

Here is where it stopped the second time:
![screen shot 2016-08-25 at 5 13 38 pm](https://cloud.githubusercontent.com/assets/445733/17992420/64ca9872-6b04-11e6-97da-43c1451e5f76.png)

The first time it stopped it got through language_classifier.tar.gz.7. And then you were right, everything failed after that. 

Thanks again.

**Comment by thatdatabaseguy** [comment]
Hmm, connections to S3 can sometimes bork at random, which may be the cause. With 10 concurrents it's certainly possible. Just added retries to the underlying curl commands with https://github.com/openvenues/libpostal/commit/01afbf80efd9baf2adbe62c97901b4fd98f8854b, which should hopefully help in future cases.

**Comment by jefffriesen** [comment]
Nice, thanks.

Btw, I love the long, super-detailed writeup on how you implemented libpostal (https://mapzen.com/blog/inside-libpostal/). Looking forward to geocoding solutions built on top of it too! 

Thanks again
